### ISSUE TITLE
博客沉淀很赞，有没有兴趣来阿里的前端团队

### ISSUE THREAD

**Issue by xiamidaxia** [laihuamin/JS-total#36]
你好，我这边是杭州阿里支付宝商家组的前端团队，我们团队正在打造一个前端基础研发体系，会涉及大量的工具制作，包括web-ide, ui自动化测试等，有兴趣可以关注这篇文章：https://zhuanlan.zhihu.com/p/34790596

如果觉得不错的话，可以联系我的个人邮箱: xiamidaxia@icloud.com

**Comment by laihuamin** [comment]
谢谢你的欣赏，到时候有机会我会试试的。
